version: '3.8'

services:
  web:
    build: .  ### Vai buildar a imagem da aplicação flask utilizando a Dockerfile presente no diretorio
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  ### Utiliza o arquivo nginx.conf para definir o redirecionamento de requisiçoes que o proxy reverso do nginx fará, enviando o acesso para a aplicação web.
    depends_on:
      - web
