### Arquivo responsavel por criar o deployment da applicação flask

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: web-app  
          image: zotti39/application_web:latest
          ports:
            - containerPort: 5000

